### ISSUE TITLE
Parsing fails for VCF with GT in header but not in FORMAT field

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/bio2zarr#267]
Here an example of a failing VCF (generated by hypothesis-vcf while testing https://github.com/sgkit-dev/hypothesis-vcf/pull/3):

```
##fileformat=VCFv4.3
##FILTER=<ID=PASS,Description="All filters passed">
##source=hypothesis-vcf-0.1.dev4+g1f4f9c2
##contig=<ID=0>
##INFO=<ID=A0,Type=Integer,Number=1,Description="Generated field">
##INFO=<ID=B0,Type=Integer,Number=1,Description="Generated field">
##FORMAT=<ID=GT,Type=String,Number=1,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
0	1	.	A	.	.	.	A0=0
```

The GT field is defined in the header, but it's not used. Note that this is the same case tested by [no_genotypes_with_gt_header.vcf
](https://github.com/sgkit-dev/sgkit/blob/02b9ce5142b21ad83d67aabf17db4f69f37c95c0/sgkit/tests/io/vcf/data/no_genotypes_with_gt_header.vcf) in sgkit, which was fixed in https://github.com/sgkit-dev/sgkit/pull/621.

The failure is:
```
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/bio2zarr-3.10/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/tom/workspace/bio2zarr/bio2zarr/vcf2zarr/icf.py", line 1082, in process_partition
    tcw.append("FORMAT/GT", variant.genotype.array())
AttributeError: 'NoneType' object has no attribute 'array'
```

**Comment by jeromekelleher** [comment]
Nice, good catch hypothesis
