### ISSUE TITLE
bool object has no attribute split when running vcf2zarr explode  

### ISSUE THREAD

**Issue by no7ren** [sgkit-dev/bio2zarr#297]
I run into the problem when converting one vcf file with command vcf2zarr explode. After some debugs, it turns out that the problem was caused by some of the 'INFO' field where at some positions they don't have any value and more important is they even don't have "=" like the following: 
MQ=4.61443;AN=120;AC=6,26;MQRankSum=1.656;**ReadPosRankSum**;DP=2423

Can you take this into account like if there is no delimiter (=), you can skip split function?

Thank you!

**Comment by jeromekelleher** [comment]
Thanks for the report here @no7ren. I think this probably is a bug, and it would really be helpful to have a minimal example to provoke it. Do you think you could concoct a very small VCF  (i.e., one data line, if possible) that provokes the issue please?

What do you get when running this through cyvcf2? We don't actually access the VCF data but depend on htslib/cyvcf2 to do the parsing.

**Comment by no7ren** [comment]
Hi, 

You can find the test file in the attachment. And one more thing I found is that the type of field matters a lot. It has no error when I change from String to Float. 

Here is the error I got:
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 1078, in process_partition
    tcw.append(field.full_name, variant.INFO.get(field.name, None))
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 806, in append
    self.field_writers[name].append(value)
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 724, in append
    val = self.transformer.transform_and_update_bounds(val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 503, in transform_and_update_bounds
    value = self.transform(vcf_value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 542, in transform
    value = np.array(list(vcf_value.split(",")))
                          ^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'split'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "vcf2zarr", line 8, in <module>
    sys.exit(vcf2zarr_main())
             ^^^^^^^^^^^^^^^
  File "python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/bio2zarr/cli.py", line 232, in explode
 Explode:   0%|                                                                       | 0.00/1.00 [00:01<?, ?vars/s]    vcf2zarr.explode(
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 1188, in explode
    writer.explode(worker_processes=worker_processes, show_progress=show_progress)
  File "python3.11/site-packages/bio2zarr/vcf2zarr/icf.py", line 1128, in explode
    with core.ParallelWorkManager(worker_processes, progress_config) as pwm:
  File "python3.11/site-packages/bio2zarr/core.py", line 301, in __exit__
    wait_on_futures(self.futures)
  File "python3.11/site-packages/bio2zarr/core.py", line 104, in wait_on_futures
    raise exception
AttributeError: 'bool' object has no attribute 'split'

 
[testcase.vcf.gz](https://github.com/user-attachments/files/18166417/testcase.vcf.gz)

**Comment by jeromekelleher** [comment]
Thanks for the test case @no7ren, this is very helpful. I'm afraid I won't get to this until the new year, but will pick it up then.

**Comment by jeromekelleher** [comment]
Thanks again for the report @no7ren, sorry it's taken a long time to get to this.

It's not totally obvious to me how this should be interpreted. Here's the header and INFO string:
```
##INFO=<ID=ReadPosRankSum,Number=.,Type=String,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
...
...MQ=5.37115;AN=8;AC=6;MQRankSum=0;ReadPosRankSum;DP=286
```

Given this is a Number=. field, I think the only reasonable interpretation here is ReadPosRankSum is a list of length 0 strings?

**Comment by jeromekelleher** [comment]
I see - the issue here is that we're using cyvcf2 here to interpret the VCF data, which is interpreting "ReadPosRankSum" as a bool and not a string. There's not a lot we can do here unless we start second-guessing what cyvcf2 is doing.

So, if we load the VCF into cyvcf2 we get some weird results:
```python
import cyvcf2
vcf = cyvcf2.VCF("testcase.vcf.gz")
print(vcf)
row = next(vcf)
print(row)
print("Value = ", row.INFO["ReadPosRankSum"])
```
gives:
```
<cyvcf2.cyvcf2.VCF object at 0x7fec681ae7a0>                                                                          
chl1    290     .       A       T       887.41  .       MQ=5.37115;AN=8;AC=6;MQRankSum=0;ReadPosRankSum;DP=286  GT:DP:FT:GQ:AD        ./.:0:.:.:.,.
                                                                                                                      
Value =  False        
```

Note that the value returned here is False, which doesn't make sense under any interpretation to me.

So - I think this is probably something that you'll need to raise upstream with cyvcf2, unless you think there's something else we should be doing with what we're getting?
